### ISSUE TITLE
Refactor Beaconizer to Act as a simple REST Layer ontop of a beacon-adapter

### ISSUE THREAD

**Issue by patmagee** [mcupak/beaconizer#8] opened 2016-06-03 15:54 UTC
Refactor the beaconizer to act strictly as a rest layer on top of a Beacon Adapter. the beaconizer should ONLY accept a single adapter and "beaconize" it, exposing the api. 

All the business logic currently in the Beaconizer project should be moved to specific adapters. The implementation detail of this should not be in the scope of the beaconizer.

Support for multiple beacons will be removd

**Comment by mcupak** [comment] 2016-06-03 16:00
Duplicate of #7.

**Closed as completed** 2016-06-17 20:46 UTC
Labels: priority:high, type:task
